name: First_worflow
on: push 

jobs: 
  first: 
    runs-on: ubuntu-latest
    steps: 

      - name: Get code
        uses: actions/checkout@v4

      - name: Print
        run : echo "First Workflow"

      - name: NPM install
        run: npm install

      - name: Lint 
        run: npm run lint
  
  second: 
    runs-on: ubuntu-latest
    needs: first
    steps: 
      - name: Print
        run : echo "Second Workflow"

      - name: NPM install
        run: npm install

      - name: Test 
        run: npm run test
  
  third:
    runs-on: ubuntu-latest
    needs: second
    steps: 
      - name: Print
        run : echo "Third Workflow"

      - name: NPM install
        run: npm install

      - name: Build 
        run: npm run build
