name: Output
on:
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]

jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - name: output
        run: echo "${{ toJSON(github.event) }}"